### PR TITLE
Test: non contributor pull request - Actions update

### PR DESCRIPTION
**Pull request by Conscript89**

### CODE REVIEW

**Comment by jkonecny12** [comment]
To maintainers: If you want deeper explanation how this works feel free to ping me. :)

**Comment by pholica** [comment]
There's no need. It was me (from personal account) testing with @velezd github actions on pull request from non-contributor account :)

**Comment by jkonecny12** [comment]
I understand that, I meant that I already did a few testing about how this behaves and if you want I can explain that to you.

**Comment by Conscript89** [comment]
Oh, I get it. The thing is that we were changing some stuff how conditions are handled in the github actions to a new way. @velezd knows more. I was interested how non-contributor pull request would behave when `if: github.repository == 'rhinstaller/permian'` is used.

**Comment by Conscript89** [comment]
Closing this pull request as it's not needed anymore.

**Pull request closed without merging**
